site_name: My personal notes

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: "1"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
